using System;

public class GridColumns {
    public string ProjectCode { get; set; } //(nvarchar(12), not null)
    public string GridKey { get; set; } //(nvarchar(40), not null)
    public string ColumnName { get; set; } //(nvarchar(30), not null)
    public string GroupName { get; set; } //(nvarchar(150), null)
    public string GroupNameEN { get; set; } //(nvarchar(150), null)
    public string Name { get; set; } //(nvarchar(150), null)
    public string VNName { get; set; } //(nvarchar(150), null)
    public string Formula { get; set; } //(nvarchar(1000), null)
    public string Params { get; set; } //(nvarchar(500), null)
    public string Note { get; set; } //(nvarchar(1000), null)
    public bool? Visible { get; set; } //(bit, null)
    public bool? Used { get; set; } //(bit, null)
    public bool? AllowEdit { get; set; } //(bit, null)
    public string Creater { get; set; } //(nvarchar(30), null)
    public DateTime? CreateTime { get; set; } //(datetime, null)
    public string Editer { get; set; } //(nvarchar(30), null)
    public DateTime? EditTime { get; set; } //(datetime, null)
    public int ColWidth { get; set; } //(int, null)
    public string Align { get; set; } //(nvarchar(10), null)
    public string DataType { get; set; } //(nvarchar(30), null)
    public string Format { get; set; } //(nvarchar(50), null)
    public string RelatedColumnName { get; set; } //(nvarchar(30), null)
    public string ValueType { get; set; } //(nvarchar(20), null)
    public string SQLF3 { get; set; } //(nvarchar(1000), null)
    public string ManyItem { get; set; } //(nvarchar(500), null)
    public bool? Groups { get; set; } //(bit, null)
    public string StoreInfo { get; set; } //(nvarchar(1000), null)
    public string FixParams { get; set; } //(nvarchar(300), null)
    public string FormatString { get; set; } //(nvarchar(100), null)
    public string FormulaCode { get; set; } //(nvarchar(1000), null)
    public string NoteUser { get; set; } //(nvarchar(1000), null)
    public string SummaryType { get; set; } //(nvarchar(30), null)
    public string FontName { get; set; } //(nvarchar(150), null)
    public string FontColor { get; set; } //(nvarchar(50), null)
    public string FontFormat { get; set; } //(nvarchar(150), null)
}
